base_config:
  input_file: input.jsonl
  save_dir: ./output/caption_conversation

# step
pre_process:
  model_id_or_path: null
  pp_func: pp_func.caption_conv.pre_process

caption:
  model_id_or_path: YOUR_PATH_TO/Qwen2.5-VL-72B-Instruct
  limit_mm_per_prompt: {'image': 5, 'video': 2}
  prompt: Please describe this image in detail.
  pp_func: pp_func.caption_conv.caption_pp

question_generation:
  model_id_or_path: YOUR_PATH_TO/Qwen2.5-72B-Instruct
  prompt: |
    Please analyze a description of an image and generate questions based on it. When designing questions, please consider the following five criteria:
    - Relevance: Ensure the questions are closely related to the image content, avoiding information beyond what the image provides.
    - Clarity: The questions should be clear and unambiguous. Avoid vague or confusing questions that may lead to multiple interpretations.
    - Answerability: Questions should be specific and answerable based on the image. Avoid questions that cannot be determined from the image.
    - Information Sufficiency: Ensure the image contains enough information to answer the questions.
    - Objectivity: Avoid questions that rely heavily on personal opinions.

    Image Description: {}
    Based on the above criteria, design 5 questions. Separate each question with a newline and output one question per line.
  pp_func: pp_func.caption_conv.question_generation_pp

respond:
  model_id_or_path: YOUR_PATH_TO/Qwen2.5-VL-72B-Instruct
  prompt: "{}"
  pp_func: pp_func.caption_conv.respond_pp
