base_config:
  input_file: input.jsonl
  save_dir: ./output/caption_gen

pre_process:
  model_id_or_path: null
  pp_func: pp_func.caption_gen.pre_process

caption:
  model_id_or_path: YOUR_PATH_TO/Qwen2.5-VL-72B-Instruct
  prompt: Please describe this image in detail.
  # prompt: 请详细描述这张图片。
  pp_func: pp_func.caption_gen.caption_pp
