base_config:
  input_file: input.jsonl
  save_dir: ./output/caption_hallucination

# step
pre_process:
  model_id_or_path: null
  pp_func: pp_func.caption_hall.pre_process

caption:
  model_id_or_path: YOUR_PATH_TO/Qwen2.5-VL-72B-Instruct
  limit_mm_per_prompt: {'image': 5, 'video': 2}
  prompt: Please describe this image in detail.
  pp_func: pp_func.caption_hall.caption_pp

devide:
  model_id_or_path: YOUR_PATH_TO/Qwen2.5-72B-Instruct
  prompt: |
    Please help me split this text into several paragraphs so that each paragraph has relatively complete semantics. Separate each paragraph with a newline character.
    Text: {}
  pp_func: pp_func.caption_hall.devide_pp

check:
  model_id_or_path: YOUR_PATH_TO/Qwen2.5-VL-72B-Instruct
  prompt: |
    Please help me check whether this text accurately describes the image.
    Text Input: {}
    Please directly output "Correct" or "Incorrect."
  pp_func: pp_func.caption_hall.merge
