base_config:
  input_file: input.jsonl
  save_dir: ./output/prompt_response_match_score

pre_process:
  model_id_or_path: null
  pp_func: pp_func.product_evolve.get_sft_data_instruction_and_response

score:
  model_id_or_path: YOUR_PATH_TO/Qwen2.5-72B-Instruct
  prompt: prompt_func.prompt_response_match_score_prompt.score_prompt
  pp_func: pp_func.product_evolve.score_pp
