base_config:
  input_file: ./input.jsonl
  save_dir: ./VLThinking

preprocess:
  model_id_or_path: null
  pp_func: pp_func.VLThinking.preprocess

caption:
  model_id_or_path: YOUR_PATH_TO/Qwen2.5-VL-72B-Instruct
  prompt: prompt_func.VLThinking.caption
  pp_func: pp_func.VLThinking.caption

cot:
  model_id_or_path: YOUR_PATH_TO/DeepSeek-R1-Distill-Qwen-32B
  prompt: prompt_func.VLThinking.cot
  pp_func: pp_func.VLThinking.cot

rewrite:
  model_id_or_path: YOUR_PATH_TO/Qwen2.5-72B-Instruct
  prompt: prompt_func.VLThinking.rewrite
  pp_func: pp_func.VLThinking.rewrite

verify:
  model_id_or_path: YOUR_PATH_TO/Qwen2.5-72B-Instruct
  prompt: prompt_func.VLThinking.verify
  pp_func: pp_func.VLThinking.verify